---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cyf03.
--- DateTime: 2025/11/22 16:17
---
-- 订单id
local voucherId = ARGV[1]

-- 用户id
local userId = ARGV[2]

local orderId = ARGV[3]

-- 优惠券key
local stockKey = 'seckill:stock' .. voucherId

-- 订单key
local orderKey = 'seckill:order' .. voucherId

-- 判断库存是否充足
-- 库存不足 返回1
if (tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end

-- 判断用户是否下单
-- sismember判断一个元素是否在集合当中
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end

--扣减库存
redis.call('incrby',stockKey,-1)

-- 将userId存入当前优惠券的set集合
-- sadd 向set集合中添加元素
redis.call('sadd',orderKey,userId)

redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0
