---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cyf03.
--- DateTime: 2025/11/22 16:06
---
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0